### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by TS000** [vintage-software/EstateSales.NET-Api#2]
The link for API Keys brings you to the client portal. After login you are sent to a place where Estate's are managed. I cant find for the life of me any place to make a key on this page.

**Comment by steve-haar** [comment]
It looks like the link is not remembered after logging in. Until we are able to get that fixed, try clicking the link after you have logged in. If you are still unable to access the page, then you are probably not set to an admin user of the organization.

**Comment by TS000** [comment]
That work around was successful. Thank you.

**Comment by atbro86** [comment]
What kind of EstateSales.NET account do you need in order to access the API Keys page? When I hit the API link in the Wiki, it just redirects me back to `/accounts/.` I have a basic account for email subscriptions.

**Comment by kevinbuhmann** [comment]
@atbro86, EstateSales.NET API keys are only available to company admins for listing eatate sales on the site.

If you run a company that holds estate sales, you can sign up on our site as a company. Other than that, I'm sorry to say that there's nothing you can do with this API as managing estate sale listings is it's only feature.

**Comment by kevinbuhmann** [comment]
I'm closing this issue as it appears it's been resolved.
