### ISSUE TITLE
SalePicture Url 

### ISSUE THREAD

**Issue by sglasser** [vintage-software/EstateSales.NET-Api#3]
Hi,

Is it possible if the item image is already hosted elsewhere to specify the image url instead of actually uploading the byte array? I see there is a Url field on the SalePicture but I'm seeing a 500 error back from server when I use that. 

Thanks

**Comment by kevinphelps** [comment]
No, this is possible.

**Comment by kevinbuhmann** [comment]
No, that is not possible. You must upload the image data to our servers.
